### ISSUE TITLE
[Ideia] Busca de Repositórios em Arquivos YAML

### ISSUE THREAD

**Issue by stephan-lopes** [guiaanonima/InfoSecTools#7]
### Título

Realizar busca dos repositórios em Arquivos YAML

## Resumo
Hoje, o código possui dentro dele, os repositórios que são instalado. Dessa forma, é ruim para quem irá utilizar ter uma visibilidade na escolha das ferramentas, bem como, em criar seus próprios pacotes para instalação automatizada.

Essa ideia, tem como proposta o uso de arquivos yaml, onde dentro dele, possuem os pacotes e repositórios que deseja ser instalado.

## Passo-a-Passo
A proposta de yaml, seria semelhante ao que teria abaixo:
```yaml
---
version: v1
kind: Package

metadata:
    name: all-in-one-nginx
    version: v1.0
    distro: linux-debian # Outras opções [linux-ubuntu, linux-kali, linux-arch]

packages:
     - name: info-gathering # Seria o latest, implicitamente
     - name: password-atack
       version: latest
     - name: web-app-tools
       version: v2.16

tools:
    - name: nginx
      version: 1.16 # Seria possível também utilizar o nginx sem o version ou latest
```

O usuário teria a escolha de usar tanto o CLI sem passar argumento, onde mostraria os packages (como acontece hoje) dentro do diretório templates:
```bash
infosectools.py
# Depois, selecionar entre as opções, qual dos pacotes deseja instalar. 
# No exemplo, seria o all-in-one-nginx.
```

Ou passar um arquivo como lista de entrada, como por exemplo: 
```bash
infosectools.py -f ./templates/all-in-one-nginx.yaml
```

Ambos devem funcionar, de maneira semelhante.

## Considerações
Ainda assim, há melhorias a serem feitas nesse YAML, como por exemplo, adicionar a opção de usar um mirror específico. Isso poderia ser feito em outro arquivo também, mas por enquanto, vamos focar escopo menor e atender o kind do package proposto. 

Melhorias nessa ideia são bem-vindas.
